version: '3.8' 
services:
  backend:
    build:
      context: ./angular
      dockerfile: Dockerfile
    container_name: asmanguler-be
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://host.docker.internal:27017/portfolio 
      JWT_SECRET: ${JWT_SECRET:-supersecretkey}
      PORT: ${PORT:-3000}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      NODE_ENV: production
    restart: unless-stopped
  frontend:
    build:
      context: ./ASM
      dockerfile: Dockerfile
    container_name: asm-fe
    ports:
      - "4200:4200" 
    depends_on:
      - backend
    restart: unless-stopped